= Logging and tracing with Context - comparing Log4j and Zipkin

== About

This is an examples project for logging and tracing with Log4j and Zipkin.

This is an add-on to a talk I presented.

English slides::
https://speakerdeck.com/ahus1/logging-and-tracing-with-context-information-log4j-zipkin-and-spring-sleuth

German slides::
https://speakerdeck.com/ahus1/logging-und-tracing-mit-kontextinformationen

English acticle published in Dutch Java User Group Java Magazine::
http://www.ahus1.de/uploads/images/16_19LoggingandTracingwithContextInformation.pdf[Logging and Tracing with Context Information]

German acticle published on Heise Developer::
https://www.heise.de/developer/artikel/Logging-und-Tracing-mit-Kontextinformation-fuer-Java-Entwickler-3686586.html[Logging und Tracing mit Kontextinformation für Java-Entwickler]

== Disclaimer

This code is presented as examples for learning and not as ready-to-use production code.

== License

Copyright 2016-2017 Alexander Schwartz

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

<http://www.apache.org/licenses/LICENSE-2.0>

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
